### ISSUE TITLE
Generating Specs 

### ISSUE THREAD

**Issue by mohameddiaa27** [adham90/command_service_object#1]
I think it would be nice if the spec files are generated from the `service_generator.rb`. They can be default but still optional.

```
$ rails g service user create update delete --no-usecase-specs --no-command-specs
```
or 

```
$ rails g service user create update delete --no-test-framework
```

**Comment by adham90** [comment]
i already added rspec test https://github.com/adham90/command_service_object/blob/master/lib/generators/service/service_generator.rb#L63 you can add minitest boilerplate test :smiley: https://github.com/adham90/command_service_object/blob/master/lib/generators/service/templates/minitest.rb.erb
