### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by mohameddiaa27** [adham90/command_service_object#2]
Since every command is meant to map to a specific action, It would be nice if the mapping is done automatically (The manual way is important too for extra customization).

We need a default service to call, and the command itself can be extracted optionally by default from `params[:action]`

```ruby
class UsersController < ApplicationController
  default_service :user_service

  def create
    cmd = command.new(user_params)
    # instead of
    # cmd = UserService::Commands::Create.new(user_params)
    ...
  end
end
```

Where the command is a method is prepended to the application controller.

```ruby
  def command(service: nil, usecase: nil)
    service ||= default_service
    usecase ||= params[:action]
    "#{service}/commands/#{usecase}".camelize.constantize
  end
```

Then we can even hook the application service call from inside the command itself.

```ruby
class UsersController < ApplicationController
  default_service :user_service

  def create
    cmd = command.new(user_params)
    result = cmd.execute
    # This return the result from
    # ApplicationService.call(cmd)
    ...
  end
end
```

**Comment by adham90** [comment]
@mohameddiaa27 checkout this commit https://github.com/adham90/command_service_object/commit/bd765cfb1552391e570e746595f845665bb5fd09  :heart_eyes: :heart_eyes: we need to add test for this commit

**Comment by mohameddiaa27** [comment]
@adham90 i love it ♥️👍🏻👌

The way I’d append the module is by using `class_eval`.

Also I think the execute method can be moved inside the command class to avoid method/action naming collisions.

**Comment by adham90** [comment]
so we need to create base class for commands to add execute method and shared logic :thinking: 
and i think in this case we will add `include Virtus.model` to the base class
can you create PR with your solution? :nerd_face:

**Comment by mohameddiaa27** [comment]
@adham90 Yes sure, I’m just not sure if it is a good solution to add the `include Virtus.model` because I guess the attributes it defines are on the class level. Let me check that out 👍🏻
